

import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "@/component/header/header";
import { ToastContainer } from "react-toastify";
import Footer from "@/component/footer/footer";
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
      </head>
            <body className={inter.className}>

         <Headers></Headers>

        {children }
        
      <Footer></Footer>
      <ToastContainer></ToastContainer>
        </body>


    </html>
  );
}
